#! /usr/bin/env python3

import sys


if len(sys.argv)==3:
    infil = sys.argv[1]
    utfil = sys.argv[2]
    fin = open(infil, 'r')
    fut = open(utfil, 'w')
    skriv = True
    for line in fin:
        if 'B31' in line:
            skriv = False
        if 'B32' in line:
            skriv = False
        if 'CPS3' in line:
            skriv = False
        if 'CPS6' in line:
            skriv = False
        if 'C3D4' in line:
            skriv = True
        if 'C3D10' in line:
            skriv = True
        if skriv:
            fut.write(line)
    fut.close()
    fin.close()

else:
    print('Usage:')
    print('only3d <infile> <outfile>')
    print('')
    
